preprocessing:
  target: HeartDisease
  features:
  - Age
  - Sex
  - ChestPainType
  - RestingBP
  - Cholesterol
  - FastingBS
  - RestingECG
  - MaxHR
  - ExerciseAngina
  - Oldpeak
  - ST_Slope
train:
  TEST_SIZE: 0.3
  VALIDATE_SIZE: 0.2
  RANDOM_STATE: 2024
  CV: 5
  alpha: 0.1
continuas:
- Age
- RestingBP
- Cholesterol
- MaxHR
- Oldpeak
discretas:
- FastingBS
categoricas:
- Sex
- ChestPainType
- RestingECG
- ExerciseAngina
- ST_Slope
optuna:
  RandomForest:
    n_estimators: 196
    max_depth: 5
    min_samples_split: 10
optimization:
  RandomForest:
    n_estimators: 50
    min_samples_split: 10
    max_depth: null
