preprocessing:
  target: quality
  features:
  - fixed acidity
  - volatile acidity
  - citric acid
  - residual sugar
  - chlorides
  - free sulfur dioxide
  - total sulfur dioxide
  - density
  - pH
  - sulphates
  - alcohol
  - Id
train:
  TEST_SIZE: 0.3
  VALIDATE_SIZE: 0.2
  RANDOM_STATE: 2024
  CV: 5
  alpha: 0.1
continuas:
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol
- Id
discretas: []
categoricas: []
optuna:
  GradientBoosting:
    n_estimators: 109
    learning_rate: 0.09192319357389454
    max_depth: 4
optimization:
  GradientBoosting:
    n_estimators: 100
    max_depth: 7
    learning_rate: 0.2
